author: D. Ashmore (Asperitas Consulting)
name: Terraform Docs Update
description: Checks that documentation has been updated on PR
inputs:
  push:
    description: 'Pushes generated documentation changes'
    default: false
  config:
    description: Terraform Docs config file
    default: .terraform-docs.yml
  gitUserName:
    description: User name to use for git commit and push
    default: github-actions[bot]
  gitEmail:
    description: User email to use for git commit and push
    default: github-actions[bot]@users.noreply.github.com
runs:
  using: composite
  steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21.x"
        cache: false

    - name: install tools
      shell: bash
      run: |
        go install github.com/terraform-docs/terraform-docs@v0.17.0

    - name: Terraform documentation generation
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}
      run: |
        echo "==> Generating Terraform documentation..."
        if [ -f $CONFIG ]; then
          export DOCSCONFIG=$(realpath $CONFIG)
        else
          export DOCSCONFIG=$(echo $CONFIG)
        fi
        find . -name '*.tf' | while read f; do dirname $f; done | sort -u | while read d; do terraform-docs -c $DOCSCONFIG $d; done

    - name: Documentation git push or reporing
      shell: bash
      env:
        PUSH: ${{ inputs.push }}
        GITNAME: ${{ inputs.gitUserName }}
        GITEMAIL: ${{ inputs.gitEmail }}
      run: |
        echo "==> Testing for changes to tracked files"
        echo PUSH=$PUSH
        git add .
        git status
        CHANGES=$(git status -suno)
        echo $CHANGES

        if [ "$CHANGES" ]; then
          echo "Repository Terraform documentation is not correct."
          echo
          git diff
          if [ "$PUSH" != "true" ]; then
            exit 1
          fi

          git config user.email "$GITEMAIL"
          git config user.name "$GITNAME"
          git commit -m "Automatic Terraform documentation update"
          git push
        fi