---
name: Code checks

on:
    pull_request:
        types: ['opened', 'reopened', 'synchronize']
    workflow_dispatch:
        inputs:
            push:
              description: Push documentation changes
              required: true
              type: boolean
              default: true

jobs:
    docs:
        name: docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              if: ${{ github.event_name == 'pull_request'}}
              with:
                ref: ${{ github.event.pull_request.head.ref }}

            - uses: actions/checkout@v4
              if: ${{ github.event_name != 'pull_request'}}

            - name: check docs
              uses: ./.github/actions/terraform-docs
              with:
                push: ${{ github.event_name == 'pull_request' || inputs.push }}

    format:
        name: format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              if: ${{ github.event_name == 'pull_request'}}
              with:
                ref: ${{ github.event.pull_request.head.ref }}

            - uses: actions/checkout@v4
              if: ${{ github.event_name != 'pull_request'}}

            - name: check formatting
              uses: ./.github/actions/terraform-format
              with:
                push: ${{ github.event_name == 'pull_request' || inputs.push }}

    validate:
        name: validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: check syntax
              uses: ./.github/actions/terraform-validate
