author: D. Ashmore (Asperitas Consulting)
name: Terraform Format
description: Checks that Terraform code has correct syntax
inputs:
  version:
    description: 'Terraform version'
    default: 1.8.0

runs:
  using: composite
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.version }}

    - name: Terraform syntax check
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}
      run: |
        echo "==> Validating Terraform syntax..."
        find . -name '*.tf' | while read f; do dirname $f; done | sort -u | while read d; do ls ; cd $d ; terraform init -backend=false ; terraform validate; done
